# version: "3"

services:
  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super369
      POSTGRES_DB: go-order-process
      DSN: "host=postgres port=5432 user=postgres password=super369 dbname=go-order-process sslmode=disable timezone=UTC connect_timeout=5"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always